### ISSUE TITLE
create_function() deprecated

### ISSUE THREAD

**Issue by dd-b** [Piwigo/Piwigo-private_share#1]
admin.php calls deprecated function create_function() about line 54. Right now, this produces a warning which is visible on the album page, but works. Next major PHP upgrade this will stop working.

Current code is:
> $tab_codes = array_map(
  create_function('$a', 'return $a["code"];'),
  $tabs
  );

This code should fix it:
>$tab_codes = array_map(
      function($a, { return $a["code"]; } ),  $tabs
 ) );

**Comment by plegall** [comment]
fixed in db35c72512083cbd44a6a289f74f97b52ad681fe
