### ISSUE TITLE
When in the settings "Warning: Attempt to read property "value" on null in ..."

### ISSUE THREAD

**Issue by tanty** [Piwigo/Piwigo-private_share#9]
When opening the "Configuration" tab of the settings page of the plugin I get this:

```
/config/www/_data/templates_c/p6jhns^5928a4e77b9e238c8e878ccd2e37e22108464a81_0.file.admin_config.tpl.php on line 79

Warning: Attempt to read property "value" on null in /config/www/_data/templates_c/p6jhns^5928a4e77b9e238c8e878ccd2e37e22108464a81_0.file.admin_config.tpl.php on line 79
">
```

This is with piwigo 13.6.0 from [linuxserver.io](https://docs.linuxserver.io/images/docker-piwigo)

**Comment by tuxroller** [comment]
Looks like same issue as here https://github.com/plegall/Piwigo-community/issues/78.
And same method to fix it: remove {$F_ACTION} in file ./plugins/private_share/template/admin_config.tpl
Line 27
`<form method="post" action="{$F_ACTION}">`     =>    `<form method="post" action="">`

And as I said in https://github.com/plegall/Piwigo-community/issues/78#issuecomment-1565256321 : don't know if something else has got broken with this fix.
